### PR TITLE
format with prettier

### PR DESCRIPTION
**Pull request by KTibow**
i hope this doesn't break anything

### CODE REVIEW

**Comment by TGWaffles** [comment]
Looks good except the 2-space indents - if you can switch those back to 4 I can approve 👍

**Comment by KTibow** [comment]
then why is prettier already listed as a dependency in `package.json` and a lot of the code 2 spaces already :suspect:

**Comment by KTibow** [comment]
oops

**Comment by TGWaffles** [comment]
> then why is prettier already listed as a dependency in `package.json` and a lot of the code 2 spaces already :suspect:

@ByteGamer

**Comment by RobertCallens** [comment]
> > then why is prettier already listed as a dependency in `package.json` and a lot of the code 2 spaces already :suspect:
> 
> @ByteGamer 

i have no idea im not home rn cant remember eighter

**Comment by KTibow** [comment]
Abandoned and conflicted

**Pull request closed without merging**
